"""initial schema

Revision ID: 59155ab7bbe6
Revises: 
Create Date: 2025-11-06 07:11:28.043687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59155ab7bbe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_session_id'), 'conversation_session', ['id'], unique=False)
    op.create_table('conversation_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='message_role_enum'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_message_id'), 'conversation_message', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_message_session_id'), 'conversation_message', ['session_id'], unique=False)
    op.create_table('conversation_image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('storage_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analysis_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analysis_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_message.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_image_id'), 'conversation_image', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_image_message_id'), 'conversation_image', ['message_id'], unique=False)
    op.create_index(op.f('ix_conversation_image_session_id'), 'conversation_image', ['session_id'], unique=False)
    op.create_table('model_usage_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('request_type', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_input', sa.Float(), nullable=False),
    sa.Column('cost_output', sa.Float(), nullable=False),
    sa.Column('cost_total', sa.Float(), nullable=False),
    sa.Column('usage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_message.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_usage_log_id'), 'model_usage_log', ['id'], unique=False)
    op.create_index(op.f('ix_model_usage_log_message_id'), 'model_usage_log', ['message_id'], unique=False)
    op.create_index(op.f('ix_model_usage_log_session_id'), 'model_usage_log', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_usage_log_session_id'), table_name='model_usage_log')
    op.drop_index(op.f('ix_model_usage_log_message_id'), table_name='model_usage_log')
    op.drop_index(op.f('ix_model_usage_log_id'), table_name='model_usage_log')
    op.drop_table('model_usage_log')
    op.drop_index(op.f('ix_conversation_image_session_id'), table_name='conversation_image')
    op.drop_index(op.f('ix_conversation_image_message_id'), table_name='conversation_image')
    op.drop_index(op.f('ix_conversation_image_id'), table_name='conversation_image')
    op.drop_table('conversation_image')
    op.drop_index(op.f('ix_conversation_message_session_id'), table_name='conversation_message')
    op.drop_index(op.f('ix_conversation_message_id'), table_name='conversation_message')
    op.drop_table('conversation_message')
    op.drop_index(op.f('ix_conversation_session_id'), table_name='conversation_session')
    op.drop_table('conversation_session')
    # ### end Alembic commands ###
